openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /sanctum/csrf-cookie:
    get:
      summary: 'Return an empty response simply to trigger the storage of the CSRF cookie in the browser.'
      operationId: returnAnEmptyResponseSimplyToTriggerTheStorageOfTheCSRFCookieInTheBrowser
      description: ''
      parameters: []
      responses:
        204:
          description: ''
      tags:
        - Endpoints
      security: []
  /:
    get:
      summary: ''
      operationId: get
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'hello, please visit /docs for documentation'
                  docs: 'http://localhost:8000/docs'
                properties:
                  message:
                    type: string
                    example: 'hello, please visit /docs for documentation'
                  docs:
                    type: string
                    example: 'http://localhost:8000/docs'
      tags:
        - Endpoints
      security: []
  /auth/login:
    post:
      summary: 'Login endpoint'
      operationId: loginEndpoint
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  description: ''
                  example: password123
                nip:
                  type: string
                  description: ''
                  example: '2121021210'
              required:
                - password
                - nip
      security: []
  /auth/logout:
    post:
      summary: ''
      operationId: postAuthLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /admin/dashboard/counts:
    get:
      summary: ''
      operationId: getAdminDashboardCounts
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Not Authorized'
                properties:
                  message:
                    type: string
                    example: 'Not Authorized'
      tags:
        - Endpoints
      security: []
  /admin/dashboard/stats/request:
    get:
      summary: ''
      operationId: getAdminDashboardStatsRequest
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Not Authorized'
                properties:
                  message:
                    type: string
                    example: 'Not Authorized'
      tags:
        - Endpoints
      security: []
  /admin/dashboard/stats/item:
    get:
      summary: ''
      operationId: getAdminDashboardStatsItem
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Not Authorized'
                properties:
                  message:
                    type: string
                    example: 'Not Authorized'
      tags:
        - Endpoints
      security: []
  /category:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Not Authorized'
                properties:
                  message:
                    type: string
                    example: 'Not Authorized'
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: quis
              required:
                - name
      security: []
  '/category/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Not Authorized'
                properties:
                  message:
                    type: string
                    example: 'Not Authorized'
      tags:
        - Endpoints
      security: []
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: voluptatum
              required:
                - name
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the category.'
        example: 1
        required: true
        schema:
          type: integer
  /item:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Not Authorized'
                properties:
                  message:
                    type: string
                    example: 'Not Authorized'
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: idnhfkffhubkalce
                merk:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: yardufokakghrtuppbouqhkl
                unit:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: lnvpvrpfjoooouht
                stock:
                  type: integer
                  description: satuan.
                  example: 11
                min_stock:
                  type: integer
                  description: ''
                  example: 2
                category_id:
                  type: integer
                  description: ''
                  example: 7
                price:
                  type: integer
                  description: ''
                  example: 15
              required:
                - name
                - merk
                - unit
                - stock
                - min_stock
                - category_id
                - price
      security: []
  '/item/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Not Authorized'
                properties:
                  message:
                    type: string
                    example: 'Not Authorized'
      tags:
        - Endpoints
      security: []
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: fyitxpxzqe
                merk:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: dgjnvauzzpshqubonvvr
                unit:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: hdszxwbxlmh
                stock:
                  type: integer
                  description: satuan.
                  example: 7
                min_stock:
                  type: integer
                  description: ''
                  example: 1
                category_id:
                  type: integer
                  description: ''
                  example: 7
                price:
                  type: integer
                  description: ''
                  example: 6
              required:
                - name
                - merk
                - unit
                - stock
                - min_stock
                - category_id
                - price
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the item.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
