openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/v1/login:
    post:
      summary: 'Login endpoint'
      operationId: loginEndpoint
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: ''
                  example: admin
                password:
                  type: string
                  description: ''
                  example: password123
              required:
                - username
                - password
      security: []
tags:
  -
    name: Endpoints
    description: ''
